name = "PrettyFormat"
version = "0.1.0"
defaultTargets = ["Format", "BaseFormatter", "LSPformat", "Bridge", "Doc", "Constraint", "ProjectFormat"]


[[lean_lib]]
name = "PrettyFormat"
root = "PrettyFormat"
srcDir = "PrettyFormat"


[[lean_lib]]
name = "BaseFormatter"
root = "BaseFormatter"
srcDir = "PrettyFormat"

[[lean_lib]]
name = "CoreFormatters"
root = "CoreFormatters"
srcDir = "PrettyFormat"

[[lean_lib]]
name = "Bridge"
root = "Bridge"
srcDir = "PrettyFormat"

[[lean_lib]]
name = "Constraint"
root = "Constraint"
srcDir = "PrettyFormat"

[[lean_lib]]
name = "Doc"
root = "Doc"
srcDir = "PrettyFormat"

[[lean_lib]]
name = "PFMT"
root = "PFMT"
srcDir = "PrettyFormat"


[[lean_lib]]
name = "LSPformat"
root = "LSPformat"
srcDir = "PrettyFormat"


[[lean_lib]]
name = "Format"
root = "Format"
srcDir = "PrettyFormat"
supportInterpreter = true

[[lean_exe]]
name = "ProjectFormat"
root = "ProjectFormat"
srcDir = "PrettyFormat"

[[lean_exe]]
name = "MissingAnalysis"
root = "MissingAnalysis"
srcDir = "PrettyFormat"
supportInterpreter = true