name = "simple_meta"
version = "0.1.0"
defaultTargets = ["runner", "PrettyFormat"]


[[lean_lib]]
name = "SimpleMeta"

[[lean_lib]]
name = "PrettyFormat"
root = "PrettyFormat"
srcDir = "PrettyFormat"

[[lean_lib]]
name = "Formatter"
root = "Formatter"
srcDir = "PrettyFormat"

[[lean_lib]]
name = "temporary_imported"
root = "temporary_imported"

[[lean_lib]]
name = "BaseFormatter"
root = "BaseFormatter"
srcDir = "PrettyFormat"

[[lean_lib]]
name = "annotations"
root = "annotations"
srcDir = "PrettyFormat"

[[lean_lib]]
name = "PFMT"
root = "PFMT"
srcDir = "PrettyFormat"


[[lean_lib]]
name = "runner"
root = "runner"
