name = "PrettyFormat"
version = "0.1.0"
defaultTargets = ["Format", "BaseFormatter", "LSPformat"]


[[lean_lib]]
name = "SimpleMeta"

[[lean_lib]]
name = "PrettyFormat"
root = "PrettyFormat"
srcDir = "PrettyFormat"

[[lean_lib]]
name = "FormatterExtension"
root = "FormatterExtension"
srcDir = "PrettyFormat"

[[lean_lib]]
name = "BaseFormatter"
root = "BaseFormatter"
srcDir = "PrettyFormat"

[[lean_lib]]
name = "CoreFormatters"
root = "CoreFormatters"
srcDir = "PrettyFormat"

[[lean_lib]]
name = "Doc"
root = "Doc"
srcDir = "PrettyFormat"

[[lean_lib]]
name = "PFMT"
root = "PFMT"
srcDir = "PrettyFormat"


[[lean_lib]]
name = "simple_imported"
root = "simple_imported"


[[lean_lib]]
name = "monadPerfImported"
root = "monadPerfImported"

[[lean_lib]]
name = "LSPformat"
root = "LSPformat"
srcDir = "PrettyFormat"


[[lean_exe]]
name = "Format"
root = "Format"
srcDir = "PrettyFormat"
supportInterpreter = true
