name = "simple_meta"
version = "0.1.0"
defaultTargets = ["runner"]


[[lean_lib]]
name = "SimpleMeta"

[[lean_lib]]
name = "PrettyFormat"
root = "PrettyFormat"
srcDir = "PrettyFormat"

[[lean_lib]]
name = "FormatterExtension"
root = "FormatterExtension"
srcDir = "PrettyFormat"

[[lean_lib]]
name = "BaseFormatter"
root = "BaseFormatter"
srcDir = "PrettyFormat"

[[lean_lib]]
name = "CoreFormatters"
root = "CoreFormatters"
srcDir = "PrettyFormat"

[[lean_lib]]
name = "PFMT"
root = "PFMT"
srcDir = "PrettyFormat"


[[lean_lib]]
name = "simple_imported"
root = "simple_imported"

[[lean_exe]]
name = "runner"
root = "runner"
supportInterpreter = true
